### ISSUE TITLE
Running on CoreOS

### ISSUE THREAD

**Issue by Maxim-Filimonov** [buildkite/docker-buildkite-agent#1]
One suggestion in your README breaks running on CoreOS:
`-v`which docker`:/usr/bin/docker`
This won't work because host operating system is using different static libs. 
See example of how we handle it now:
https://github.com/play2lead/build-agent

**Comment by toolmantim** [comment]
Ah yes. So the reason I added that method was to avoid version-mismatches between daemon and command. But yeah, that's not going to work.

Do you think docker should be installed in the base lib? I guess we can create different images if people want older versions of docker.

Also, nice Docker compose hacking :)

`sed -i.bak s/fig/docker-compose/g /etc/buildkite-agent/bootstrap.sh`

**Comment by Maxim-Filimonov** [comment]
Yeah you might need different tags for different version. Something like buildkite/agent:1.5.0 gives docker version 1.5.0. See [this one](https://github.com/DanielDent/docker-meteor) for example 
Heh told you it's simple to switch to docker-compose :)

**Comment by toolmantim** [comment]
Yeah, it's the compose is sitting in a branch on my laptop here. 

As for tags, we'll also be tagging our own versions too. Would be it insane to have two levels of tagging?

**Comment by Maxim-Filimonov** [comment]
We have 3 :dancers:

**Comment by toolmantim** [comment]
What does that even look like?

**Comment by Maxim-Filimonov** [comment]
image:sha
image:latest
image:env (staging,prod) 
You might not need to go that fancy. We are fighting against RAILS_ASSET host and it's uphill battle with Docker :(

**Comment by toolmantim** [comment]
So… perhaps…

```
buildkite/agent:latest
buildkite/agent:latest-docker
buildkite/agent:1.0
buildkite/agent:1.0-docker
```

and not worry about the docker versioning. Basically "here's one with the latest Docker included" (which is just the base image, with Docker added), or if you want a specific old version of Docker you just make your own from the base image…

The base image should probably leave out docker compose as well then.

**Comment by toolmantim** [comment]
Also the agent should run on CoreOS… so perhaps the Dockerised version should be CoreOS?

**Comment by Maxim-Filimonov** [comment]
Hm.. CoreOS inside CoreOS that might work :) The only problem is it's really hard to install anything on the CoreOS itself as there is no package manager. The install.sh script you have in the agents docs works however, I have tried it on CoreOS.

**Comment by toolmantim** [comment]
Cool. And I'm assuming docker-compose works as well?

**Comment by Maxim-Filimonov** [comment]
I think so i didn't get to docker-compose stage :\

**Comment by Maxim-Filimonov** [comment]
So update on this we have fully working agent on coreos with the following cloud config, feel free to add this to your docs:
https://gist.github.com/Maxim-Filimonov/3d9831d3d10735b2dc6f
