### ISSUE TITLE
$SSH_PRIVATE_RSA_KEY_PATH still does not help for Kubernetes

### ISSUE THREAD

**Issue by rimusz** [buildkite/docker-buildkite-agent#22]
passing `$SSH_PRIVATE_RSA_KEY_PATH` as env variable and sshkey as secret in k8s RC still does
not allow to call remote server via ssh, it asks for sshkey password and remote VM password too.
Making a new docker image based on buildkite-agent and adding sshkey there then it works as suppose to work.

**Comment by toolmantim** [comment]
What's the easiest way to give it a test so we can fix what's broken?

**Comment by rimusz** [comment]
I need to find what is different between two setups :)

**Comment by toolmantim** [comment]
I mean, what's the easiest way we can set up a test environment ourselves?

**Comment by rimusz** [comment]
you need to test it on Kubernetes cluster, the easiest to setup is Google GKE one.
I can provide replication controller and secret manifests to test it out

**Comment by toolmantim** [comment]
Yeah if you could send them those, that'd be great

**Comment by toolmantim** [comment]
I believe this should work AOK now :+1:
