### ISSUE TITLE
include rsync

### ISSUE THREAD

**Issue by rimusz** [buildkite/docker-buildkite-agent#29]
Would be handy to have `rsync` included in alpine and ubuntu based images

**Comment by rimusz** [comment]
ping @toolmantim and @keithpitt

**Comment by toolmantim** [comment]
Looks like it'd only add 488KB to the image. What was the use case @rimusz?

**Comment by rimusz** [comment]
handy to have, specially running some tasks in Kubernetes which need to sync files around

**Comment by lox** [comment]
Closed in #52.
