### ISSUE TITLE
Mounting folders inside docker within docker

### ISSUE THREAD

**Issue by Maxim-Filimonov** [buildkite/docker-buildkite-agent#3]
Just found an interesting issue which you might want to mention in the README. 
It's pretty much required to mount /builds from /builds to buildkite-agent when using dockerised tests.
Details:
We run our tests inside docker container. Which essentially result in a buildkite-agent launching docker-compose with volumes mounted to run tests. 
The volume path it will try to mount during run will be absolute path on buildkite-agent. While as we are proxying to the host docker it docker will use host path to find directory not buildkite-agent path.
You might be able to solve this somehow via volumes_from command when starting docker-compose containers from buildkite. Don't have enough magic juice to tell you how :(

But meanwhile as a workaround this fixes mount issue
`-v /builds:/builds`

**Comment by toolmantim** [comment]
Neat. If there's a way of getting the current docker container name, we could mount the volume of the docker agent into the build docker.

So in our own [agent's fig.yml](https://github.com/buildkite/agent/blob/8b6fb8edca1753bbbabe30f3b715895891d83255/fig.yml) we're linking in the build dir…which is one way of getting around the problem. Also it's super handy at passing through the environment variables too, and expanding the volume path.

I was trying to do the same with [buildkite/terminal](https://github.com/buildkite/terminal) the other day, but without the fig/docker-compose. I added a `BUILDKITE_DOCKER_BUILD_VOLUME` to add the `-v` but then I had the env export problem too, if you want to use artifact upload from inside the build scripts.

Hrmm…

**Comment by Maxim-Filimonov** [comment]
The way you are doing in your fig.yml is exactly the same as we do it. The problem will happen when you try to run `fig run app tests.sh` on a dockerised build-agent.
It will interpolate `.` as path inside the agent. While the real docker host is not the agent container but the host machine instead.

**Comment by Maxim-Filimonov** [comment]
Thinking more about it I think the valid solution for this problem is a data volume container. See 
[docker docs](https://docs.docker.com/userguide/dockervolumes/)
This will give you the data container

```
docker create -v /builds --name buildkite-agent-data centos
```

Then when running docker container you just add --volumes-from

```
docker run .... --volumes-from buildkite-agent-data
```

And then when running docker-compose bootstrap needs to pass this too:

```
docker-compose run --volumes-from buildkite-agent-data
```

If I manage to configure our build agent via coreos fleet over this weekend I can try to add data container there. I'll let you know how it goes.

**Comment by toolmantim** [comment]
Hrmm yeah… or:

```
docker run --volumes-from $(current container name) myscript.sh
```

But wouldn't that just be the same as…

```
docker run -v /builds:/builds myscript.sh
```

**Comment by blueimp** [comment]
The data container approach works well in my tests with a custom buildkite-agent docker image:
https://github.com/blueimp/buildkite-agent

Mounting a data-container instead of a hosts volume makes the containers independent of the host, which makes scaling easier for multiple docker engines.
It also makes testing easier on Mac OS X, where the docker host is a virtual machine and not the OS X machine itself.

**Comment by toolmantim** [comment]
@blueimp that image you've made looks really nice.

cc @lox

**Comment by blueimp** [comment]
Thanks!
It incorporates a number of docker best practices collected over the last couple of months.
We're using it for the CI tests of our application (`qipp` on buildkite.com), which itself consists of a number of docker containers.

**Comment by toolmantim** [comment]
Cool, so we've got the bind mounted version in the readme, and I've linked to @blueimp's buildkite-agent docker image from the readme too
