### ISSUE TITLE
Docker 1.12 support

### ISSUE THREAD

**Issue by jared-mackey** [buildkite/docker-buildkite-agent#39]
Docker 1.12 has been released and offers some cool new features. I'd like to start using those in my Docker file.

**Comment by toolmantim** [comment]
Hey Jared. Are you running the agent itself in Docker?

**Comment by jared-mackey** [comment]
Yes.

**Comment by toolmantim** [comment]
Cool, just checking! I'll get this updated and pushed out shortly for you.

**Comment by jared-mackey** [comment]
Awesome. Thanks so much

**Comment by jared-mackey** [comment]
@toolmantim any update on this?

**Comment by toolmantim** [comment]
I started a branch but there doesn't seem to be a 1.12.0 package in Alpine Linux yet?

**Comment by jared-mackey** [comment]
I just looked and it seems to be on the edge branches.  I wonder how we get them to update it as 12.1 is officially released.

**Comment by jared-mackey** [comment]
I was able to get them to update it. It is now on the edge branch of pgks. You can view it [here](https://pkgs.alpinelinux.org/packages?name=docker&branch=&repo=&arch=&maintainer=).

**Comment by toolmantim** [comment]
Thanks to @sj26's work on buildkite/agent#373 this is now live! 🎉

**Comment by toolmantim** [comment]
Thanks for getting the Alpine package updated!

**Comment by jared-mackey** [comment]
@toolmantim Thanks a bunch! This is working great now!
