### ISSUE TITLE
switch to overlay driver by default on newer docker versions

### ISSUE THREAD

**Issue by jared-mackey** [buildkite/docker-buildkite-agent#41]
Using the overlay driver increases build speed dramatically. My 3 minute cached docker build went to a 10 second cached docker build. Using the environment variable `DOCKER_DRIVER='overlay'` enables it. I know it is supported on the current Ubuntu image. I am not sure about the alpine version.

**Comment by toolmantim** [comment]
Thanks for the report. We kind of cover this in the Readme:

``` bash
docker run -it \
  -e BUILDKITE_AGENT_TOKEN=xxx \
  --privileged \
  -e DIND=true \
  -e DOCKER_DAEMON_ARGS="-s overlay" \
  buildkite/agent
```

We'll most probably be deleting Docker from these images (#38), and provide a separate image based on it that gives you Docker inside the agent image itself… and for that we can default to `overlay` driver.

I'll close this for now, given we cover it in the readme.
