### ISSUE TITLE
Agent continues to run if DIND docker daemon dies

### ISSUE THREAD

**Issue by robholland** [buildkite/docker-buildkite-agent#43]
We're having a problem with one of our builds where the DIND docker daemon that buildkite uses is getting OOM killed. Unfortunately when the docker daemon gets killed all the processes it started continue to run. This means that although the agent claims to be up, it isn't able to process any jobs, continues to consume large amount of memory via the orphaned containers and requires manual intervention to kill the buildkite container.

The agent should notice that the DIND daemon has been killed and die, any future docker builds will fail on that agent.

**Comment by toolmantim** [comment]
Thanks for the report!

We've now removed the DIND support from the Docker image. We're letting people add DIND support themselves now, although we haven't updated the docs.

This is something to keep in mind for then, but I'll close this for now and it doesn't directly affect this image anymore.
