### ISSUE TITLE
Tag the builds

### ISSUE THREAD

**Issue by martinheidegger** [buildkite/docker-buildkite-agent#54]
When looking for a way to see how a specific docker image tag was built I have had a hard time to identify want to look at. It would be awesome if there was a branch (or tag) for each build available in docker hub.

**Comment by lox** [comment]
We've moved packaging to https://github.com/buildkite/agent/tree/master/packaging/docker/linux, and also added more granular tagging, see https://hub.docker.com/r/buildkite/agent/tags/.
