### ISSUE TITLE
tzdata package

### ISSUE THREAD

**Issue by nightah** [buildkite/docker-buildkite-agent#63]
Is there any chance we might be able to get the tzdata package added to the buildkite-agent: https://github.com/buildkite/docker-buildkite-agent/blob/6a77d6b1e118c1e15b2386b290e66d69c7a7a202/stable/Dockerfile#L3-L16

With this we can pass in an environment variable "TZ" to the docker container to control the timezone of the build agent, which can then be utilised elsewhere in scripts, etc.

I'm happy to submit a PR just want to gauge if this would be considered.

**Comment by lox** [comment]
Sure, we'd accept a PR.
